server {
    listen 127.0.0.1:8088;
    listen 172.17.0.1:8088;
    server_name 127.0.0.1 localhost;

    root /var/www/jisutech.space;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|png|svg|jpg|jpeg|webp|ico)$ {
        expires 30d;
        add_header Cache-Control "public";
    }
}
