DELETE FROM proxy_host
WHERE domain_names LIKE '%jisutech.space%';

INSERT INTO proxy_host (
  created_on,
  modified_on,
  owner_user_id,
  is_deleted,
  domain_names,
  forward_host,
  forward_port,
  access_list_id,
  certificate_id,
  ssl_forced,
  caching_enabled,
  block_exploits,
  advanced_config,
  meta,
  allow_websocket_upgrade,
  http2_support,
  forward_scheme,
  enabled,
  locations,
  hsts_enabled,
  hsts_subdomains
) VALUES (
  datetime('now'),
  datetime('now'),
  1,
  0,
  '["jisutech.space","www.jisutech.space"]',
  '172.17.0.1',
  8088,
  0,
  0,
  0,
  0,
  0,
  '',
  '{"letsencrypt_agree":false,"dns_challenge":false,"nginx_online":true,"nginx_err":null}',
  0,
  0,
  'http',
  1,
  '[]',
  0,
  0
);
